---
title: "Random Forest Tumor Prediction"
format: html
editor: visual
---

# Setup

```{r}
pacman::p_load(
  wrappedtools, tidyverse, here, conflicted, ggforce, ggbeeswarm, 
  flextable,caret, tidymodels, gmodels, easystats, yardstick, kknn, 
  rpart, rpart.plot, randomForest, future.mirai, xgboost, ranger
)

conflicts_prefer(
  dplyr::select,
  dplyr::filter,
  dplyr::slice,
  dplyr::filter,
  dplyr::lag,
)
```

# Data loading

```{r}
rawdata <- readRDS("data/cervical.RDS")
predvars <- ColSeeker(rawdata, "_")
```

# Modeling
```{r}
set.seed(2026)
rf_folds <- vfold_cv(
  rawdata, 
  v = 5, 
  strata = Tissuetype, 
  repeats = 20)

rf_recipe <- recipe(rawdata) |>
  update_role(Tissuetype, new_role = "outcome") |>
  update_role(all_of(predvars$names), new_role = "predictor") |>
  update_role(SampleID, PatID, new_role = "id")

rf_grid <- expand.grid(mtry = 10:50) |>
  as_tibble() 

rf_spec <- rand_forest(
  trees = 10000,
  mtry = tune()
) |>
  set_engine("ranger", importance = "impurity") |>
  set_mode("classification")

rf_workflow <- workflow() |>
  add_recipe(rf_recipe) |>
  add_model(rf_spec)

# Fit the model to the data
plan(mirai_multisession, workers = availableCores() - 2) 
rf_results <- rf_workflow |>
  tune_grid(
    resamples = rf_folds,
    grid = rf_grid,
    metrics = metric_set(roc_auc, accuracy, kap)
  )
plan(sequential)

# See the top performing models
rf_results |>
  show_best(metric = "accuracy") |>
  select(-.config, -.estimator) |>
  mutate(across(
    where(is.numeric), 
    \(x) roundR(x, 5, drop0 = TRUE))) |>
  flextable()

# Select the best parameters based on your preferred metric
rf_best <- rf_results |>
  select_best(metric = "accuracy")

# Visualize the tuning results
rf_results |>
  collect_metrics() |>
  ggplot(aes(x = mtry, y = mean)) +
  geom_line() +
  geom_point() +
  facet_grid(rows = vars(.metric)) +
  theme_bw()

rf_results |>
  collect_metrics(summarize = FALSE) |>
  filter(.metric == "accuracy") |>
  ggplot(aes(x = factor(mtry), y = .estimate)) +
  geom_boxplot(outlier.alpha = 0) +
  geom_beeswarm(
    alpha = 0.3,
    aes(color = .config == rf_best$.config)
  ) +
  scale_color_manual(
    "best model",
    values = c("darkgrey", "orange"),
    labels = c("no", "yes")
  ) +
  theme_bw()

rf_results |>
  collect_metrics(summarize = FALSE) |>
  filter(.metric == "accuracy") |>
  ggplot(aes(x = factor(mtry), y = .estimate)) +
  stat_summary(
    fun.data = mean_sdl,
    aes(color = .config == rf_best$.config)) +
  geom_point(aes(color = .config == rf_best$.config)) +
  scale_color_manual(
    "best model",
    values = c("darkgrey", "orange"),
    labels = c("no", "yes")
  ) +
  theme_bw()

# Update the workflow with those best parameters
final_workflow <- rf_workflow |>
  finalize_workflow(rf_best)

# Fit to the entire data set (or use test split)
final_fit <- final_workflow |>
  fit(data = rawdata)

final_out = extract_fit_engine(final_fit)

importance <- tibble(
  Variable = names(final_out$variable.importance),
  Importancescore = final_out$variable.importance
) |> 
  mutate(Variable = fct_reorder(Variable, Importancescore))

ggplot(importance, aes(x = Variable, y = Importancescore)) +
  geom_col() +
  coord_flip()

ggplot(importance, aes(x = Variable, y = Importancescore)) +
  geom_col() +
  coord_flip() +
  geom_hline(yintercept = max(importance$Importancescore) / 2,
             color = "red",
             linetype = 2) +
  geom_hline(yintercept = max(importance$Importancescore) * 0.75,
             color = "blue",
             linetype = 2)

# Arbitrary threshold
importance |> filter(Importancescore > 0.1) |>
  ggplot(aes(x = Variable, y = Importancescore)) +
  geom_col() +
  coord_flip() +
  geom_hline(yintercept = max(importance$Importancescore) / 2,
             color = "red",
             linetype = 2) +
  geom_hline(yintercept = max(importance$Importancescore) * 0.75,
             color = "blue",
             linetype = 2)

importance |> 
  filter(Importancescore > (max(importance$Importancescore) / 2)) |>
  ggplot(aes(x = Variable, y = Importancescore)) +
  geom_col() +
  coord_flip() +
  geom_hline(yintercept = max(importance$Importancescore) / 2,
             color = "red",
             linetype = 2) +
  geom_hline(yintercept = max(importance$Importancescore) * 0.75,
             color = "blue",
             linetype = 2)

test_predicted <- final_fit |>
  augment(new_data = rawdata) |> 
  rename_with(\(x) str_remove(x, "^.pred_"), starts_with(".pred_"))
```

# Model Evaluation

```{r}
tidy_metrics <- metric_set(
  accuracy, kap,
  f_meas, roc_auc, 
  mn_log_loss)

tidy_metrics(test_predicted,
  truth = Tissuetype, estimate = class,
  Tumor
) |>
  flextable()

CrossTable(test_predicted$class,
  test_predicted$Tissuetype,
  prop.chisq = F, prop.t = F,
  format = "SPSS"
)

confusionMatrix(
  test_predicted$class,
  test_predicted$Tissuetype,
  positive = "Tumor"
)
```